#!/bin/sh
# steam-wrapper-dwm
# 2023-06-05 [22:57]

# Contributors:
#   Coltrane Willsey <cwillsey06@gmail.com>

main () {
	APPID=''
	case "$1" in
		-n|--name) APPID="$(get_steam_appid "$2")" ;;
		-i|--id) APPID="$2" ;;
		[?]) print_usage ;;
	esac
	run_steam_app "$APPID"
}

get_steam_appid () {
	# thank you, https://steamcommunity.com/app/221410/discussions/0/1621724915820500210/#c2790495976033726339
	find /hdd/SteamLibrary/steamapps/ -maxdepth 1 -type f -name '*.acf' -exec \
		awk -F '"' '/"appid|name/{ printf $4 "|" } END { print "" }' {} ';' \
		| column -t -s '|' \
		| sort -k 2 \
		| grep -i "$1"
}

run_steam_app () {
	steamcmd='steam'
	# assume flatpak is in use if a steam binary doesn't exist
	[ ! -f "$(command -v steam)" ] \
		&& steamcmd='flatpak run com.valvesoftware.Steam'
	"$steamcmd" -applaunch "$1"
}

x_init () {
	# use .xinitrc if it exists
	xinitrc="$HOME/.xinitrc"
	[ -f "$xinitrc" ] \
		&& . "$xinitrc" \
		&& return 0
	exec pipewire-pulse &
	exec pipewire &
	exec dwm &
}

print_usage () {
	printf '%s\n' \
		'steam-wrapper-dwm [-n|--name {appname}] [-i|--id {appid}]'
}

main "$@"

